#!/usr/bin/env php
<?php

use Vados\MigrationRunner\Start;

$autoloadFiles = [
        __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
];

foreach ($autoloadFiles as $file) {
    if (file_exists($file)) {
        define('COMPOSER_AUTOLOAD', $file);
        break;
    }
}
unset($file);
if (!defined('COMPOSER_AUTOLOAD')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );
    die(1);
}
require COMPOSER_AUTOLOAD;

(new Start($argv))->process();